# Generated by Django 3.1.5 on 2021-01-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movrotativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movrotativo',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
